name: Build and Release

# Se ejecuta SOLO cuando publicas una Release en GitHub
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build for Windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist